### ISSUE TITLE
Viewer CSS and JavaScript aren't served gzip-compressed

### ISSUE THREAD

**Issue by paulschreiber** [documentcloud/document-viewer#47]
The DocumentCloud Viewer CSS and JavaScript aren't served gzip-compressed from the Amazon S3 servers.

Example URL:

    http://s3.amazonaws.com/s3.documentcloud.org/viewer/viewer.js

Response Headers:

    Date: Mon, 22 Dec 2014 17:42:35 GMT
    ETag: "c461f0969585f2aaff54e405967d12be"
    Last-Modified: Tue, 16 Dec 2014 18:18:14 GMT
    Server: AmazonS3
    x-amz-id-2: ukt2TSsLb5DM0RUlxdYsr/1pozp/gsREOVRJ9xlWIlPlniZjqA3vf8ZACmCu7mP95yWV78oKMXs=
    x-amz-request-id: 16053EED6EADE536

While Amazon S3 doesn't support on-the-fly compression, you can compress the files locally and then upload them. You'll need to add the `Content-Encoding: gzip` header to the files.

A better solution might be to [use CloudFront](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html).

**Comment by reefdog** [comment]
Totally legit, but since that's a platform/hosting issue (not a Document Viewer issue itself), closing this in favor of your issue here: https://github.com/documentcloud/documentcloud/issues/207
