### ISSUE TITLE
don't use document.write to insert script

### ISSUE THREAD

**Issue by paulschreiber** [documentcloud/document-viewer#58]
Chrome emits this warning:
A Parser-blocking, cross-origin script, https://assets.documentcloud.org/viewer/viewer.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.

Here's the code in question:

```
/* Request the viewer JavaScript. */
document.write('<script type="text/javascript" src="//assets.documentcloud.org/viewer/viewer.js"></scr' + 'ipt>');
```

Please replace this with `var s = document.createElement('script');` or similar.

**Comment by reefdog** [comment]
Thanks @paulschreiber, we were just chatting about this today. Definitely high-priority thanks to [Chrome's impending removal](https://developers.google.com/web/updates/2016/08/removing-document-write) in the next version (for 2G mobile users).

**Comment by knowtheory** [comment]
Done!  See https://github.com/documentcloud/documentcloud/pull/418
